### ISSUE TITLE
Start missions on flotilla only in the area/deck the robot has been localized in

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#1002]
**Describe the improvement you would like to see**
At the moment, regardless of where the robot is localized, it is possible to start a mission. So if the robot is in AP330 and we send a mission in AP130, the mission will be sent and probably the first task will fail because the robot can't calculate a path between those points.  

I believe there should be a check in flotilla for this and also a dialog should appear letting the user know that he is trying to initiate a mission in an area different from where the robot was localized. 

Or another possibility is that the queue should filter the missions and only send missions in the area the robot has been localized into. But having the robot being localized in an area and potencially start a mission immediately that was scheduled maybe days ago seems a bit risky.

With the portals now, maybe we can check for decks and not only for Areas. But someone offshore needs to check that if the robot was localized in AP110 and we are sending it to AP120 on the first task, it can get there without a problem. 

**How will this change existing functionality?**
Better control of the mission queue and the start of missions.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by andchiind** [comment]
Seems closely related to #998
