### ISSUE TITLE
Improve error handling on fetching echo missions

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1008]
**Describe the improvement you would like to see**
When fetching all echo missions with the `EchoController`, the status codes `502` or `500` is returned if an ecxeption is catched: 

```
try
        {
            var missions = await _echoService.GetAvailableMissions(plantCode);
            return Ok(missions);
        }
        catch (HttpRequestException e)
        {
            _logger.LogError(e, "Error retrieving missions from Echo");
            return new StatusCodeResult(StatusCodes.Status502BadGateway);
        }
        catch (JsonException e)
        {
            _logger.LogError(e, "Error retrieving missions from Echo");
            return new StatusCodeResult(StatusCodes.Status500InternalServerError);
        }
```

In the frontend, it will look like the request is spinning forever, even though the request does not repeat/retries. In this situation, it should instead display an error message to the user. 

**How will this change existing functionality?**
No change in functionality, just giving user meaningful error messages. 

**How will this improvement affect the current Threat Model?**
Should not affect threat model, but be aware of what to display in frontend

**Comment by andchiind** [comment]
We likely want to combine this with the banner alert in the figma, and simply close the missions dialog. We currently have a banner for failed missions in FailedMissionAlertView.tsx, but this can be generalised. We probably also want to place it at the bottom of the header instead of just on the front page.
