### ISSUE TITLE
Default text in dropdown does not adjust to page size

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1009]
**Describe the bug**
A small bug, but it will look better with a better adaption to different screen sizes. How will this look on iPhone?

**To Reproduce**
iPad mini 5th gen, Edge bowser, Flotilla version in prod per. 18. sept 2023, English language

**Expected behavior**
Flotilla should be readable and look nice also on narrow screens as iPad and iPhone. A sugesstion is to look at the EDS dropdown components with text on top of the box. 

**Screenshots**
![InkedImage](https://github.com/equinor/flotilla/assets/21355793/98714309-eec7-42e2-9c7b-a38f69494e80)

**Comment by oysand** [comment]
#976 Will alter this quite a bit. Let's see if this is still a problem later

**Comment by mrica-equinor** [comment]
This is no longer relevant
