### ISSUE TITLE
Deck Inspections loaded with Installation

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/flotilla#1030]
**Describe the improvement you would like to see**
The Deck Inspections section in the frontend should only be loaded when an installation is chosen.

<img width="1510" alt="Screenshot 2023-09-26 at 16 05 36" src="https://github.com/equinor/flotilla/assets/74666192/15dbc7f3-eac7-4c62-8f79-66f97b28ee2e">

**Comment by oysand** [comment]
No longer an issue
