### ISSUE TITLE
Add area column and rerun button to mission history table

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1060]
**Describe the improvement you would like to see**
Add area column and "add to queue"-button to table in mission history. 

Design inspiration:
![image](https://github.com/equinor/flotilla/assets/33518988/24b26bef-ac4b-47fb-b941-5a8545b170f2)

**How will this change existing functionality?**

**How will this improvement affect the current Threat Model?**
N/A

**Comment by prasm313** [comment]
Area column made in PR #1193.

**Comment by prasm313** [comment]
Rerun button added in PR #1327.
