### ISSUE TITLE
Missions on inspection plan change position every second or so

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#1062]
**Describe the bug**
When clicking on a deck to see missions in the inspection plan, the listed missions seemingly randomly change positions in the list every second or so. This makes it difficult to click on one mission in the list.

**To Reproduce**
Click on a deck that holds several missions. Observe the missions changing place.

**Expected behavior**
The missions under a deck should have a fixed position based on either:
a) Longest time since mission is run on top
b) Alphabetical order

**Screenshots**

**Comment by andchiind** [comment]
It will no longer change positions once [the signalR PR](https://github.com/equinor/flotilla/pull/1041) is merged, but it will anyways be good to have a consistent ordering
