### ISSUE TITLE
Missions that are started but cancelled is registered as ran in inspection plan

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#1063]
**Describe the bug**
When a mission started from inspection plan is cancelled, it will register as completed in the inspection plan overview

**To Reproduce**
Run missions in inspection plan, and cancel one that has ran a tag.

**Expected behavior**
A bit unsure, might require discussion, but some system to log what tags are not run when mission is cancelled.

**Screenshots**

**Comment by andchiind** [comment]
This is now addressed in https://github.com/equinor/flotilla/pull/1041 by renaming lastRun to lastSuccessfulRun and only updating upon successful completion.
