### ISSUE TITLE
Isar changed to idle and mission was registered as done in flotilla, but status did not go to available

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#1070]
**Describe the bug**
After finishing a mission which was partially successful, the log on isar says that the mission ended and status was changed to idle. The mission was also changed to done in flotilla, but the robot status stayed as busy.

**To Reproduce**
This happened when running a custom mission which had one tag fail, but it is hard to say if this is relevant. It occured in prod. There were other missions waiting in the queue, but none of these started after the last mission ended.

**Expected behavior**
When a mission ends and the robot is idle in Isar, the flotilla backend should update the status to available so that a new mission can start.

**Screenshots**
Log in Isar:
![image](https://github.com/equinor/flotilla/assets/20266900/047c76a0-de77-4f65-8cfc-6c2752c0f567)
Log in flotilla backend shortly after it should have become available (seems to be a token issue):
![image](https://github.com/equinor/flotilla/assets/20266900/be02691f-d58b-4a34-b371-ee59dfff13bf)

**Comment by aestene** [comment]
Will be resolved by #1089
