### ISSUE TITLE
Add logs to application insight for frontend

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#1077]
**Describe the improvement you would like to see**
At the moment we only do console logging in the frontend. We should change this to a logger so the logs can be sent to application insights and be seen in the CICD system

**How will this change existing functionality?**
Make it easier to degbug frontend bugs in our environments

**Comment by andchiind** [comment]
Relevant information: https://learn.microsoft.com/en-us/azure/azure-monitor/app/javascript-sdk?tabs=npmpackage

**Comment by UsamaEquinorAFK** [comment]
Closed: https://github.com/equinor/flotilla/pull/1320

**Comment by UsamaEquinorAFK** [comment]
Robotics Infrastructure: 
https://github.com/equinor/robotics-infrastructure/pull/379
https://github.com/equinor/robotics-infrastructure/pull/380
