### ISSUE TITLE
Robot status does not update

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1084]
**Describe the bug**
The robot status (Available, Offline, etc) does not updated automatically in flotilla when the robot changes status (for example when it is switched on/off). The robot updates between available and busy as needed, the issue is currently limited to online/offline.

**To Reproduce**
Open flotilla in prod. Switch on/off robot and observe in frontend that the status is not updated. 

**Expected behavior**
The status should be updated automatically in flotilla reflecting the actual state of the robot. At the moment, status changes needs to be done manually through the swagger API. 

**Screenshots**

**Comment by aestene** [comment]
Will be addressed by #1089
