### ISSUE TITLE
Order missions when scheduling inspection plan

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1091]
**Describe the new feature you would like to see**
When a mission plan is scheduled, all mission in that inspection plan is scheduled in random order. Consider to order the missions. 

**Describe the solution you'd like**
Missions can be ordered to complete missions at area/decks in a systematic order. Some things to consider:

- Bundle mission by area
- Prioritize missions that has not been run in a long time (if the time of the last run of the missions differs by only a few days, it is probably better to sort by area)

**How will this feature affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by oysand** [comment]
To be adressed in #1021
