### ISSUE TITLE
Remove some skipped tests

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1121]
**Describe the improvement you would like to see**
Remove some skipped tests in [backend/api.test/EventHandlers/TestMissionEventHandler.cs](https://github.com/equinor/flotilla/pull/1113/files#diff-0a1ca8f8cc015387c57bbc3c17e754c757094014c27dba42c9eef5345f5d61a0)

```
#pragma warning disable xUnit1004
        [Fact(Skip = "Awaiting fix for testing with database")]
#pragma warning restore xUnit1004
```

**How will this change existing functionality?**
Some skipped tests will no longer be skipped.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
Removed in recent PR
