### ISSUE TITLE
Remove .env file from docker image

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#113]
**Describe the bug**
The .env file is copied into the docker file.

**To Reproduce**
Add a .env file to the backend folder and run the docker-compose.

**Expected behavior**
Environment variables should be passed through the docker-compose and not be copied into the containers.

**Screenshots**

**Comment by aestene** [comment]
Simplest solution is to add the `.env` to a `.dockerignore` file.

**Comment by oysand** [comment]
Agreed, this in combination with passing the variables through the docker-compose should be sufficient
