### ISSUE TITLE
Setup authentication and authorization for Flotilla

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#117]
**Describe the new feature you would like to see**
Authentication and authorization should be added to the frontend and backend components. Note that the backend component already has this but there may be need for changes.

**Describe the solution you'd like**
oAuth2 + OpenID Connect.

**How will this feature affect the current Threat Model?**
Important part of the threat model.

**Comment by GodVenn** [comment]
This should probably be implemented using
https://github.com/AzureAD/microsoft-authentication-library-for-python
