### ISSUE TITLE
Removing missions from the queue bug

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#1181]
**Describe the bug**
If we schedule a mission with shockwave for example, when I click on the remove mission from the queue button, the mission only disappears when I refresh the page. This does not happen for placebot.

**To Reproduce**
Schedule mission with shockwave and remove it from the queue.

**Expected behavior**
The mission should be removed without having to refresh the page.

**Screenshots**
In this picture I had already confirmed that I wanted to remove the mission from the queue and the dialog had been closed.

![Image](https://github.com/equinor/flotilla/assets/108514046/d1f1d294-2c5c-4472-b129-77d30dcd54f8)

**Comment by andchiind** [comment]
Everything is being updated correctly, including receiving the signalR message and applying it to the context state. The only issue is that the updated context state (missionListsContext.tsx) does not trigger a rerender in MissionQueueView.tsx. I'm investigating that now
