### ISSUE TITLE
Replace semaphores in scoped services with a shared semaphore in a hosted service

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#1195]
**Describe the bug**
Semaphores are being ignored since they are local to the current scoped service instance. Each time a different dependency injection is done, a new semaphore is created.

**To Reproduce**
Set the safezone status off and on several times while debugging. Updating the robot state is not truly being protected by a mutex.

**Expected behavior**
A semaphore should block any thread from accessing the protected code region. This can be done by storing them in hosted services which only have one instance at a time (as long as flotilla only uses one server at a time).

**Screenshots**

**Comment by andchiind** [comment]
A singleton might also work instead of a hosted service

**Comment by andchiind** [comment]
The only remaining problematic Semaphore is in RobotService.cs

**Comment by oysand** [comment]
Consider removing the semaphore

**Comment by UsamaEquinorAFK** [comment]
https://github.com/equinor/flotilla/pull/1323
