### ISSUE TITLE
Extract scope/roles from token, use this to enforce RBAC on the backend

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#1208]
**Describe the new feature you would like to see**
Extract the roles/claim from token sent to backend. Use the extracted information to add RBAC.

**Describe the solution you'd like**
A user should only be able to see information from the asset where the user has access. Currently, we have one group for all users, and no role based access control on the backend API. We should add a feature to read the token sent with requests, extract roles/scope, and use this to decide whether the user has access to the requested information or not. 

Should add functionallity on (almost?) all endpoints that checks if the user has access mapped to some list of existing roles.

**How will this feature affect the current Threat Model?**
More granular access gives a more secure application in principle.

**Comment by oysand** [comment]
Already fixed
