### ISSUE TITLE
Add documentation for running tests

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#121]
**Describe the improvement you would like to see**
Add documentation for how to run tests in Flotilla backend and frontend.

**How will this change existing functionality?**
No functionality change.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by tsundvoll** [comment]
Documentation is already in place for how to run the backend tests. No tests are currently in place for frontend. Closing this issue and suggesting we add documentation when tests are added to the frontend.
