### ISSUE TITLE
Remove default Robot constructor

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1220]
**Describe the improvement you would like to see**
The default robot constructor in `Robot.cs` is not really in use and can be removed

**How will this change existing functionality?**
Not much, but will make the code more readable

**How will this improvement affect the current Threat Model?**
N/A

**Comment by UsamaEquinorAFK** [comment]
What do you mean ? Its being used in initdb.cs I think (snap attched below).


![Image](https://github.com/equinor/flotilla/assets/110888193/e1e9e6c6-7b7b-488e-88de-998a304f455b)

**Comment by andchiind** [comment]
I tried removing it, but entity framwork seemed to want to have a default constructor 

![Image](https://github.com/equinor/flotilla/assets/20266900/59dbf03e-a04b-47ee-9785-ba5550242f2d)

I am also not sure if this needs to be prioritised, so I'm moving it to TODO

**Comment by andchiind** [comment]
@tsundvoll I hope you don't mind me closing this issue for the above reasons
