### ISSUE TITLE
Implement endpoint to query if robot is in safe position

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/flotilla#1241]
**Describe the new feature you would like to see**
An endpoint in the backend that checks if a given robot is in its safe position

**Describe the solution you'd like**
There can be a property in the `Robot` object `RobotInSafePosition`. 
Alternatively, it can check if the last mission run was a mission either a to return to safe position or return home and was successful

**Comment by oysand** [comment]
Try to use mission queue frozen as an indicator, reopen/create new issue if this is not sufficient
