### ISSUE TITLE
Change name from "Enabled" to "isarConnected"

### ISSUE THREAD

**Issue by prasm313** [equinor/flotilla#1249]
Describe the improvement you would like to see
Change the name of the robot parameter "Enabled" to "isarConnected".

How will this change existing functionality?
It will be more clear what this parameter actually is telling us. We have other parameters that this parameter can be confused with ("Available", "Offline", "Idle").

**Comment by andchiind** [comment]
This could be a good change on the backend, but I think it's still best to keep it as Enabled in the frontend models since the frontend should ideally not need to care about the existence of Isar
