### ISSUE TITLE
Add role based access to Flotilla

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#125]
**Describe the improvement you would like to see**
Manage acceess to Flotilla through role based access using Azure AD roles.

**How will this change existing functionality?**
User will be required to be added to groups in order to use Flotilla. It will be possible to granulate access on endpoints.

**How will this improvement affect the current Threat Model?**
Unauthorized access and autdated access will be mitigated to a larger degree.

**Comment by MortFred** [comment]
Discuss what roles we should have, and what access should be given to them.

**Comment by tsundvoll** [comment]
Roles can be assigned when necessary. Closing this card.
