### ISSUE TITLE
Robot status is not always updated correctly

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1250]
**Describe the bug**
Sometimes when the robot is done with a mission, it stays in "Busy" even though the mission is done.

Sometimes the robot is Available, there are no missions in Ongoing Missions, there are one mission in Mission Queue, and the robot will not start the mission.

Suggestions for what may be the reason:
* Race conditions when writing / reading from database
* Missing MQTT messages on status updates from ISAR
* Broker goes down and reconnects 

**To Reproduce**
1. Schedule a mission with isar-robot
2. See that it finishes, but the robot stays in Busy

**Expected behavior**
Robot should be set to Available

**Screenshots**

**Comment by prasm313** [comment]
See Onenote page "Busy bug" for 5 documented bugs.

**Comment by oysand** [comment]
Completed

**Comment by aestene** [comment]
Closed by #1279
