### ISSUE TITLE
Add certificate-based communication between Flotilla and Isar (HTTPS)

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#126]
**Describe the improvement you would like to see**
Add certificate-based communication between Flotilla and Isar (HTTPS)

**How will this change existing functionality?**
Communication between modules will require a certificate in order to be validated.

**How will this improvement affect the current Threat Model?**
Communication between modules will be encrypted, mitigating man-in-the-middle attacks.

**Comment by tsundvoll** [comment]
Holding off this issue until we will deploy the solution. Closing.
