### ISSUE TITLE
Make area required in missionRun

### ISSUE THREAD

**Issue by UsamaEquinorAFK** [equinor/flotilla#1271]
**Describe the bug**

Area is null in the snapshot below, it should be made required in the database models. 
![Image](https://github.com/equinor/flotilla/assets/110888193/58924da1-cdf7-4203-a5de-582f7a203eed)

**To Reproduce Steps to reproduce the behavior:**
Run dev backend swagger 

**Expected behavior A clear and concise description of what you expected to happen.** 
MissionRuns should have areas.

**Comment by andchiind** [comment]
We might want to do this after https://github.com/equinor/flotilla/issues/950
