### ISSUE TITLE
RobotCard overflows if the RobotName is too big

### ISSUE THREAD

**Issue by UsamaEquinorAFK** [equinor/flotilla#1307]
**Describe the bug**
The robot name overflows from the robot card if it is too big

**To Reproduce**
Add a new robot from Dev database with a huge name and check. 

**Expected behavior**
The name should stay inside the card possibly adapt by decreasing text size. 

![Image](https://github.com/equinor/flotilla/assets/110888193/6c2a0399-ab99-440e-940e-14e6799027c4)

**Comment by tsundvoll** [comment]
Not sure the best ting is to adapt by decreasing text size, I think capping the robot name, for example like "THEMANNNN..." is better, possibly also adding tooltip when hovering over the name showing the full name.

Adding the UX tag

**Comment by UsamaEquinorAFK** [comment]
https://github.com/equinor/flotilla/pull/1310

**Comment by UsamaEquinorAFK** [comment]
![Image](https://github.com/equinor/flotilla/assets/110888193/624a013f-494c-4003-b008-7c3b275f4fc7)
