### ISSUE TITLE
Reading DevUserId from .env file does not work

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#1322]
**Describe the bug**
When setting DevUserId in the .env file in the backend folder it is not read in. This is apparent as the singalR messages does not reach the frontend with updates. To get it to work I needed to edit the environment variable in the appsettings.local file.

**To Reproduce**
Add Local__DevUserId='some-name' into the .env file at the backend folder. Run the system from a terminal and schedule a mission. Check if the updates are automatic or if you need to refresh the page to see updates.

**Expected behavior**
Expect that one can add the environment variable to the .env file.

**Screenshots**

**Comment by andchiind** [comment]
It works everytime when using the environment variables in the launch.json file for vscode. This is not a solution, I am just pointing out that it is odd that there is a difference. It might be that the variables in the normal .env files are being ignored in preference for some other set of environment variables.
