### ISSUE TITLE
`event.robot_id` and `event.report_id.robot_id` is not always the same 

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#133]
**Describe the improvement you would like to see**
Should there be a constraint such that the robot id must be the same?

**How will this change existing functionality?**
This will remove conflicting robot ids in events

**How will this improvement affect the current Threat Model?**
No change

**Comment by vetlek** [comment]
I think this is an issue that can only be solved by being careful when creating events/reports and make sure it is consistent. Might be something in SQLAlchemy, but think this can be closed
