### ISSUE TITLE
Align text left on ghost buttons

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1331]
**Describe the improvement you would like to see**
When we use buttons, things get centered when it wraps. This is often not desired on ghost buttons like these.
![image](https://github.com/equinor/flotilla/assets/33518988/3d62053f-7fe9-4d1d-9707-8aa8f3268eac)

![image](https://github.com/equinor/flotilla/assets/33518988/d93dbd4f-5c3e-42e5-8358-900aa6e7b3d1)

Can use this in a style to fix
`    text-align: left;
`
**How will this change existing functionality?**
Looks nicer

**How will this improvement affect the current Threat Model?**

**Comment by prasm313** [comment]
Code looks good to me. Also tested it with different resolutions - looks nice!

I have found the same issue in the RobotPage:

![Image](https://github.com/equinor/flotilla/assets/147414449/10a24226-f8de-411c-b741-e3719eee2072)

Safe zone button:

![Image](https://github.com/equinor/flotilla/assets/147414449/5b2832f7-cb68-4caa-bff3-6076de96eaf7)

And History page:

![Image](https://github.com/equinor/flotilla/assets/147414449/94b11034-d2d7-43fe-be31-47d5a29d8800)

Can join you in getting this PR through on Monday.
