### ISSUE TITLE
Robot has status offline if the broker restarts

### ISSUE THREAD

**Issue by prasm313** [equinor/flotilla#1359]
**Describe the improvement you would like to see**
If the broker goes down and is restarted, the robots has "offline" as their status. If the robot is available or busy when the broker restarts this should be visible in Flotilla.

**How will this change existing functionality?**
Robots will not be stuck in offline. Will not be necessary to manually set status as Available through swagger. The users would not need to contact us if the broker has restarted.  

**How will this improvement affect the current Threat Model?**
N/A

**Comment by Afonso-2403** [comment]
Could updating the robot status in [OnIsarRobotHeartbeat](https://github.com/equinor/flotilla/blob/116ae51d675578026bfcf204ed94a2ffb06cb124/backend/api/EventHandlers/IsarConnectionEventHandler.cs#L60) if the robot is not enabled solve this problem?
The only thing is that as of now the robot status is not contained in the heartbeat.

**Comment by tsundvoll** [comment]
Blocked waiting on improved communication between ISAR and Flotilla. This includes some new states in ISAR. It also means we can rely on one of the messages instead of the combined status message.

**Comment by tsundvoll** [comment]
Ready to be retested

**Comment by tsundvoll** [comment]
Still an issue. Consider using the "heartbeat" to check regularly for a change in status.
