### ISSUE TITLE
Move installation filtering of robots

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1366]
**Describe the improvement you would like to see**
Currently robots are filtered by installation several places in the frontend. As installationcode varies between lower letter and capital letter, the installationcode needs to be made lower letter before comparison in the filters. This needs to be remembered every time a installation filter is made.

Suggest moving the filtering to one place. Preferably to the backend.
 
**How will this change existing functionality?**
Less prone to bugs and less repeated code

**How will this improvement affect the current Threat Model?**

**Comment by UsamaEquinorAFK** [comment]
Made it lower case upon access from database https://github.com/equinor/flotilla/pull/1390

**Comment by UsamaEquinorAFK** [comment]
![Image](https://github.com/equinor/flotilla/assets/110888193/c1a1b1d4-40ce-4538-b2d5-9431d7622c9d)

Works
