### ISSUE TITLE
Remove unused localization feature

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1369]
_Consider if more testing of the new localization feature should be tested before removal_

**Things to remove**
Remove localization from robotPage. This would include deleting of LocalizationDialog.tsx and LocalizationSection.tsx which is within the RobotPage folder.

In addition postLocalizationMission function from apiCaller and the corresponding endpoint in backend should be deleted.

**Comment by UsamaEquinorAFK** [comment]
https://github.com/equinor/flotilla/pull/1371
