### ISSUE TITLE
The MissionFail banner shows up before we have selected any installation

### ISSUE THREAD

**Issue by UsamaEquinorAFK** [equinor/flotilla#1375]
Describe the bug
The failed mission banner shows up at the installation selection page. 
![Image](https://github.com/equinor/flotilla/assets/110888193/6942123e-1926-49b2-8838-713eefcaf06f)

To Reproduce
Run frontend and wait a few secs before selecting an installation

Expected behavior
Should not show any warnings before we select an installation, the user doesnot need to see warnings from un-selected installations.

**Comment by andchiind** [comment]
It shows up since you have selected Huldra. This is likely since it is cached for you. I will try to hide it for the frontpage though

**Comment by UsamaEquinorAFK** [comment]
Ah but we should wait till we press the confirm installation button before showing the installations. I think.
