### ISSUE TITLE
StartTime and currentArea on missionPage is sometimes wrong/missing

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1381]
**Describe the bug**
Initially Area and Start time is correct but when the mission updates the area becomes undefined and start time becomes an hour off. 

Likely cause for area disappearing is that API call to get missionRun provides a MissionRunResponse (which is what the frontend expects), while signalR provides a MissionRun. 

**To Reproduce**
Start mission and go to mission page - Note area and start time
Wait for mission to update - Note area and start time

**Expected behavior**

**Screenshots**
Initially:
![image](https://github.com/equinor/flotilla/assets/33518988/6900135d-7bb4-487b-8f81-777f9cab7f05)

After update:
![image](https://github.com/equinor/flotilla/assets/33518988/49f7b791-54fd-4f32-860d-f916c408c577)

**Comment by andchiind** [comment]
Good catch, signalR should be sending a MissionRunResponse
