### ISSUE TITLE
Robot shown as offline even though Isar is working fine

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#1389]
**Describe the bug**
Even though Isar finished the last mission OK and is still sending info messages, it is shown as offline in Flotilla.

**To Reproduce**
Remove the timeouts in initiate_mission in isar-robot, then run several missions. When I noticed it, I had a breakpoint in OnMissionUpdate, which paused execution for around 5-10 seconds. This should not break the system, so if this pause was the cause of the issue then it is still problematic.

**Expected behavior**
As long as a robot is still reporting that it is online, Flotilla should not show it as offline.

**Screenshots**
![image](https://github.com/equinor/flotilla/assets/20266900/d644602f-e0db-4144-96a1-83abe1493ed4)
![image](https://github.com/equinor/flotilla/assets/20266900/4d6e8842-8f85-4a80-a925-b5ec0b8305cc)

**Comment by oysand** [comment]
Handled in #1359
