### ISSUE TITLE
Error message card bug/improvement

### ISSUE THREAD

**Issue by prasm313** [equinor/flotilla#1393]
**Describe the bug**
The error card does not adjust height when the error message is long.

Actions:
- Make cards with flexible height to make text fit
- Make the numbers fit better into the text
- Adjust the text alignment to the left

**To Reproduce**
Set pressure threshold in initDB.cs to a high value.
LowerPressureWarningThreshold = 0.08f,

**Screenshots**

![Image](https://github.com/equinor/flotilla/assets/147414449/cfbaa831-d1a8-44a8-850f-180fae6278d6)

**Comment by Pagla-Dasu** [comment]
If the issue still prevails, do assign me this, I would like to work on this.
Also the pull request guide for contributors are not working, so do mention the message I have to give for the pull request.

**Comment by prasm313** [comment]
Hi @Pagla-Dasu! Thank you for your interest in contributing, but at the moment we don't have the code ready to be able to have open source contributions. Ref #1046. 

Regards, Petter

**Comment by Pagla-Dasu** [comment]
Okay, Thank you.
