### ISSUE TITLE
The .env file should work even if it has commented lines

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#1404]
**Describe the bug**
Currently the way the .env file is being processed in the backend assumes that all lines are to be read and processed so no commented lines can be present in teh file.

**Comment by UsamaEquinorAFK** [comment]
https://github.com/equinor/flotilla/pull/1424

**Comment by anetteu** [comment]
This is still open but marked as done on the board. Moving to new for the team to close it or put it back on the board.

**Comment by tsundvoll** [comment]
Done
