### ISSUE TITLE
Add topic listener process

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#144]
**Describe the new feature you would like to see**
A topic listener process (insert better name here) should be added in order to listen to communication from ISAR / the robot over MQTT or through API calls if necessary to update the current status of executing missions, ISAR state and robot availability. 

This process should listen to relevant topics and update objects (reports and robots) in the database when new information is received.

**Describe the solution you'd like**
Although there is no required solution it is most likely another thread being spun up at startup in `main`. Which listens to predefined topics. Keep in mind that events on topics will lead to this thread modifying the database so thread safe thinking should be important.

**How will this feature affect the current Threat Model?**
Not affected.

**Comment by vetlek** [comment]
Some work on this have already been done in #208
