### ISSUE TITLE
Crash when using drop-down menu

### ISSUE THREAD

**Issue by prasm313** [equinor/flotilla#1443]
**Describe the bug**
Flotilla frontend crashes when using a drop-down menu either on the Samsung padlet (non compliant device where one in the robotics team is logged in), or when using "Toggle device tool" on PC. This happens both locally and in Aurora. Does not happen on compiant iPhone and iPad.

Error message: https://react.dev/errors/185?invariant=185

**To Reproduce**
Go to Flotilla staging frontend, press F12, choose "Toggle device tool", click a dropdown menu (for example "Add predefined Echo mission"), choose one of the options.

**Expected behavior**
Flotilla should not crash.

**Screenshots**

**Comment by tsundvoll** [comment]
Might be an issue with the EDS component, contact the support team there

**Comment by prasm313** [comment]
EDS team contacted on Slack

**Comment by prasm313** [comment]
> Might be an issue with the EDS component, contact the support team there
EDS team contacted on Slack

**Comment by prasm313** [comment]
Fixed in PR #1516.
