### ISSUE TITLE
Make return-to-home more robust

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1469]
**Describe the improvement you would like to see**
Return-to-home have several issues:
- [x] If arm is moved the robot will try to schedule a return-to-home mission. The mission will fail and do nothing as the robot is missing current area, but the scheduling attempt shouldn't happen at all. #1466 
- [ ] If robot is turned off without being allowed to complete return-to-home mission it will start a return-to-home when it gets started again. Should there be some timer that de-localizes the robot after a certain time if nothing happens (idle/offline?). Related to #1450 
- [x] #1464 

How can we make return-to-home behavior more robust?

In addition, I am adding this to the epic because I believe it is somehow related and would be good to get it all implemented in one go. 
- [x] #1459 

**How will this change existing functionality?**

**How will this improvement affect the current Threat Model?**

**Comment by andchiind** [comment]
Replaced by other issues. This is no longer relevant.
