### ISSUE TITLE
Mission is pending when its task is successful

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1475]
Localization mission doesn't start and stays as pending while corresponding localization task is successful.

Front page:
![image](https://github.com/equinor/flotilla/assets/33518988/edba6623-350e-48c0-beca-9e03964614f1)

Mission page:
![image](https://github.com/equinor/flotilla/assets/33518988/306c20c3-821e-441b-82df-b909beb2c07b)

**Comment by oysand** [comment]
Fixed in #1476
