### ISSUE TITLE
Improve installation selection page appearance on iPhone

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1520]
**Describe the improvement you would like to see**
Improve appearance on iPhone and small screens. Drop down menu is very narrow.

**How will this change existing functionality?**
Improve first impression of Flotilla. 

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.
![IMG_6039](https://github.com/equinor/flotilla/assets/21355793/43e9cb6d-64e6-4006-a944-12e56dd72c3e)

**Comment by prasm313** [comment]
Solved in #1451

**Comment by tsundvoll** [comment]
Already fixed in next release
