### ISSUE TITLE
Operator fails to delete mission from queue on iPhone

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1526]
**Describe the bug**
Configuration: Operator user access, iPhone, safari 

Tried to delete mission from the queue many times. The operator confirmed the deletion of the mission, but did not succeed. The following error banner appeared: 

<img width="349" alt="Screenshot 2024-04-07 at 17 18 11" src="https://github.com/equinor/flotilla/assets/21355793/50c192d0-bd5b-4311-ac23-1ab2c51802be">

The mentioned missions were removed from the queue successfully with the configuration dev (admin) access, iPad, safari. 

**To Reproduce**
Configuration: Operator user access, iPhone, safari. Queue all mission on a deck. Then, try to remove a mission from the queue. 

**Expected behavior**
The mission should be removed from the queue

**Screenshots**

**Comment by tsundvoll** [comment]
Need a quick discussion about what should happen when a mission is deleted / removed, and which access should be required.

**Maybe this action should be possible to do with user access**. Specifically deleting / removing missions from the "Pending" missions can have a separate endpoint?

**Comment by oysand** [comment]
This should allow operators to remove mission runs: #1532
