### ISSUE TITLE
Add narrow screen message also on history page

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1541]
**Describe the improvement you would like to see**
This message is shown at the top of the predefined mission table (which is actually adjusted to the screen)

<img width="301" alt="Screenshot 2024-04-10 at 08 15 48" src="https://github.com/equinor/flotilla/assets/21355793/c426bfe4-0bf5-44ad-b3db-173973b48ff4">

I suggest to add this message on top of the table on the history page, which is not adjusted to narrow screen 

**How will this change existing functionality?**
No change, just providing information where it is relevant

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by Eddasol** [comment]
Already fixed
