### ISSUE TITLE
Use v4 of the setup-dotnet GitHub Action

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#1542]
**Describe the improvement you would like to see**
We are currently using actions/setup-dotnet@v1 many places; swap these with actions/setup-dotnet@v4

**How will this change existing functionality?**
Will utilize node 20 instead of node 16 (ref. https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**How will this improvement affect the current Threat Model?**
N/A

**Comment by haakonsf** [comment]
#1594
