### ISSUE TITLE
Add dialogs when pressing the Safe Zone button

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#1544]
**Describe the improvement you would like to see**
Currently the Figma sketch has dialogs when pressing the send robots to Safe Zone button.

**How will this change existing functionality?**
Functionality should remain the same.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by mrica-equinor** [comment]
![Image](https://github.com/equinor/flotilla/assets/108514046/4bc1f899-7fd7-40c8-88d6-6646341fc954)

Text:

Sende robot til sikker sone

Du er i ferd med å sende robotene til en sikker sone og dermed stoppe alle pågående oppdrag. Robotene vil fortsette på oppdragene når du bekrefter at det er trygt a fortsette.  

Er du sikker på at du vil sende alle robotene til en sikker sone?

**Comment by haakonsf** [comment]
https://github.com/equinor/flotilla/commit/0caeae6b7c54f79cde0e6982619517916a6bab3d closes this issue
