### ISSUE TITLE
Backend crashes if we remove a mission from the queue that has just started

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#1548]
**Describe the bug**
If we click the remove mission from queue button just when the mission is starting, the status will be ongoing instead of pending but the ongoing card and pending mission card haven't re-rendered. As a consequence, the backend crashes. 

This should not happen, the exception should be caught and a message to the frontend should say that the mission wasn't able to be removed because it already started. Possibly ask the user if it wants to stop the mission.

**To Reproduce**
Remove the first mission in the queue just when the localization is finishing.

**Expected behavior**

**Screenshots**

**Comment by tsundvoll** [comment]
Seems like it would be OK to let the desired behaviour here be that the mission will start (it will not be removed / stopped) and then the operator would need to cancel the ongoing mission instead.
