### ISSUE TITLE
Timestamp for last completed mission is also updated when the mission is canceled

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1555]
**Describe the improvement you would like to see**
In the mission menu, there is a timestamp for when the mission was last completed. This timestamp is updated every time an execution of that mission is completed. This happens also if the mission was cancelled and actually never or just partly executed.

On the history page, it makes sense to have this timestamp named "last compelted", as it also provide the context of that particular mission execution.

In the mission menu, it does not provide this context, and it refers to "last execution of that mission". Could it be an improvement to show the timestamp of the last _successfully_ completed mission, and not the last completed mission in the mission menu?

**How will this change existing functionality?**
No change, just more accurate information

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by oysand** [comment]
First step only update last succssfull mission run once OnMissionUpdate reports successfull
