### ISSUE TITLE
Implement alert feature

### ISSUE THREAD

**Issue by prasm313** [equinor/flotilla#1560]
**Describe the new feature you would like to see**
Implement the notification/alert feature so that the users have an overview of the status of the missions and robots. Some of the frontend work is already done in this closed, non-merged PR #1645.

**Describe the solution you'd like**
Figma sketch:

![Image](https://github.com/equinor/flotilla/assets/147414449/fecff059-ab9b-447f-ba94-870069b181e0)

**How will this feature affect the current Threat Model?**
N/A

**Comment by anetteu** [comment]
Consider #1087 when implementing this

**Comment by anetteu** [comment]
Suggest to add button to the battery and pressure warnings: `Stop missions and drive home`.

**Comment by prasm313** [comment]
If the alert is regarding a robot, the user should be sent to the robot page when clicking the alert. Clicking alerts related to missions should send the user to missionRun page.

**Comment by prasm313** [comment]
The work has started in PR #1645.

**Comment by haakonsf** [comment]
Frontend display implemented with no functional change to alert generation or banner alerts. See comment in #1592 for more details.

**Comment by tsundvoll** [comment]
Considered done for now. Create new issue if adjustments are wanted
