### ISSUE TITLE
Consider to change or remove re-run functionality

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#1606]
**Describe the improvement you would like to see**
When re-running a mission from the history, it fails as no localization mission is scheduled. I suggest that this function is removed, or preferably, fixed by scheduling a localization mission.

**Comment by andchiind** [comment]
The localization mission issue should no longer be an issue, as rerunning missions are treated the same as any other mission. I therefore think we can keep the rerun functionality and address any other bugs separately.
