### ISSUE TITLE
Pop-up for confirming placement of robot can overflow out of webpage

### ISSUE THREAD

**Issue by haakonsf** [equinor/flotilla#1611]
**Describe the bug**
When scheduling a mission "Confirm placement of robot" pop-up flows out of the page. This makes it hard for the user to confirm the placement or close out of the pop-up as the buttons are out of reach with no scrolling functionality. The issue is only relevant when using a laptop. One way of reaching the buttons and closing the button is by pressing tab until the close button is reached.

**To Reproduce**
Schedule all missions on a deck in staging on a laptop.

**Expected behavior**
The pop-up should not flow out of the page.

**Comment by Eddasol** [comment]
Duplicate of #1600
