### ISSUE TITLE
Needs to confirm localization even if the robot is already running a mission on the same deck

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1650]
**Describe the bug**
Needs to confirm localization even if the robot is already running a mission on the same deck. Localization shouldn't be necessary when the robot is currently running a mission

**To Reproduce**
1. Schedule a mission on some deck
2. Schedule an additional mission on the same deck
3. Note the popup when scheduling the second mission

**Expected behavior**
There shouldn't be a localization confirmation popup is the robot is already localized and running a mission

**Screenshots**

**Comment by andchiind** [comment]
Related to this [#1655](https://github.com/equinor/flotilla/issues/1655)

**Comment by andchiind** [comment]
Closing it as fixing [#1655](https://github.com/equinor/flotilla/issues/1655) should also fix this
