### ISSUE TITLE
Scheduling a mission during the first mission in the queue still prompts localisation popup

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#1654]
**Describe the bug**
Since the robot is not localised until it has completed a mission, the popup asking the user to ensure that the robot is in the right place still shows up when scheduling missions while this first mission is running.

**To Reproduce**
Run a mission, schedule another mission whilst the first one is running.

**Expected behavior**
The popup should not appear while the robot is running a mission, only when it is expected to be in the localisation pose.

**Screenshots**

**Comment by Eddasol** [comment]
Duplicate of #1650
