### ISSUE TITLE
Say failed to localize if canceling a mission

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#1657]
**Describe the bug**
When canceling a missions there becomes a banner saying "Failed localization mission".

There are two issues with this:
1. As canceling doesn't have anything with localization to do (and the localization step was completed and successful), this is a misleading message and needs to be improved
2. Canceling a mission shouldn't lead to a failure message as nothing actually failed, it was just purposely cancelled

**How to reproduce**
1. Start a mission
2. Cancel the mission (after the first step such that the localization should be good)
![Image](https://github.com/equinor/flotilla/assets/33518988/66c7cbfe-f2c2-4489-9828-5f38bc443272)

3. Note banner popping up
![Image](https://github.com/equinor/flotilla/assets/33518988/3f77047c-4c94-44e7-9509-77cdec298b9c)

**Comment by mrica-equinor** [comment]
This issue is a consequence of this: 
https://github.com/orgs/equinor/projects/85?pane=issue&itemId=69123918

**Comment by andchiind** [comment]
Closed as duplicate. See above comment
