### ISSUE TITLE
Migrate from Create React App to a modern solution (proposed Vite).

### ISSUE THREAD

**Issue by EinarUeland** [equinor/flotilla#1798]
**Describe the improvement you would like to see**
Migrate from Create React App (react-scripts) to a modern maintained build environment. Proposed to use Vite which is quite popular within Equinor - including in Pointilla

**How will this change existing functionality?**
Not changes to functionality. Benefits:  a more robust modern infrastructure. Potentially faster build times and more. 

**How will this improvement affect the current Threat Model?**
Will probably remove node vulnerability warnings. 
Eliminating outdated dependencies.

**Comment by andchiind** [comment]
See #1539
