### ISSUE TITLE
Flotilla frontend to Isar backend data flow

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#185]
**Describe the new feature you would like to see**
Implement a view in frontend that lets us see the active robots from Isar.

**Describe the solution you'd like**
We need to coordinate the models from both Flotilla frontend and Flotilla backend, as well as with the [Isar](https://github.com/equinor/isar) models through the [openapi specification](https://github.com/equinor/flotilla-openapi). 
A react view to display these models will also have to be implemented.
Finally, authentication flow between Flotilla backend and Isar has to be validated

**How will this feature affect the current Threat Model?**
The data flow will be authenticated from Isar to end user using the user's group and the corresponding scope.

**Comment by vetlek** [comment]
Task too broad. Closing issue and rather create smaller issues.
