### ISSUE TITLE
Look into importing MQTT message models from ISAR to Flotilla

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#211]
**Describe the new feature you would like to see**
Currently we are "copying" the MQTT message models from ISAR into classes in flotilla backend.
A possible improvement to this could be to somehow import them.

**Describe the solution you'd like**
We could maybe include the models in versioning, giving alerts if the model has changed in ISAR when attempting to communicate from Flotilla with outdated models.

**How will this feature affect the current Threat Model?**

**Comment by vetlek** [comment]
A possible solution is using something like [Protobuf](https://developers.google.com/protocol-buffers) to define messages and generate models. This is used in MQTT Sparkplug to define messages (Sparkplug might be an opportunity in itself, but have some overhead that might not be necessary).

**Comment by GodVenn** [comment]
Not needed
