### ISSUE TITLE
Backend crashes when using docker

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#221]
**Describe the bug**
When running Flotilla using docker the backend crashes. It seem that the app does not have permission to read '/app/.IdentityService'.

**To Reproduce**
Run the following command: docker-compose up --build backend

**Expected behavior**
The backend should be able to run when running in docker.

**Screenshots**
![image](https://user-images.githubusercontent.com/32652118/169783019-a209086e-5bf5-4e63-83a5-a47f0d51d08d.png)

**Comment by GodVenn** [comment]
This is most likely an issue with the usage of `DefaultAzureCredentials` as the credential handler for the backend, and we are surely not the first to encounter this issue so there is probably an easy fix to this.
