### ISSUE TITLE
Update robot status

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#234]
**Describe the new feature you would like to see**
When missions are started and finished the robot status should change between busy and available.

**Describe the solution you'd like**
When the robot is in a mission it should say busy in the database so that the ScheduledMissionEventHandler does not try to schedule the next mission.

**How will this feature affect the current Threat Model?**
This should not effect the threat model.

**Comment by anetteu** [comment]
This is possibly easier to implement with a better alignment of IDs between flotilla and ISAR. Consider looking at #263 and https://github.com/equinor/isar/issues/293 before solving this issue.
