### ISSUE TITLE
Show video stream in frontend

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#248]
**Describe the new feature you would like to see**
The frontend should give access for users to watch a selected video stream from a selected video.

**Describe the solution you'd like**
The frontend should query the backend for the desired stream URL based on the user input.
The stream could be sent through RTMP, maybe we should use https://www.ovenmediaengine.com/ome .

**How will this feature affect the current Threat Model?**

**Comment by MortFred** [comment]
We are missing a websocket video stream to consume in frontend. This task should wait until we have a working video websocket.
