### ISSUE TITLE
Handle HttpRequestException when connecting to ISAR

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#255]
**Describe the bug**
When making a request to ISAR through IsarService and the ISAR instance is unavailable we get an HttpRequestException which is unhandled.

**To Reproduce**
- Start Flotilla
- Use any endpoint towards ISAR when ISAR is not running

**Expected behavior**
Exception should be handled and reported to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/14331473/175497583-1896cbb3-e6d8-4c52-9f28-9e05786d71d4.png)

**Comment by GodVenn** [comment]
This should probably be related to issue #278 , maybe mark the robot as disabled/unavailable whenever we get this exception as it implies that ISAR is offline
