### ISSUE TITLE
Handle case when scheduled mission fails to start

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#280]
**Describe the new feature you would like to see**
When a scheduled mission currently fails to start, it is retried instantly and infinitely. 
We should figure out how to handle scheduled missions failing. 

**Describe the solution you'd like**
Some options:
- Retrying a couple of times, and then marking them as failed and leaving it to the end-user to decide (frontend)
- Moving them to a later time slot
- Panic

**How will this feature affect the current Threat Model?**

**Comment by sondreo** [comment]
Mark as failed, and leave to user.

**Comment by anetteu** [comment]
Blocked,  awaiting database context fix #322

**Comment by MortFred** [comment]
Fixed by #322, should be tested.

**Comment by GodVenn** [comment]
This has been solved by a combination of various pull requests.
Failed missions are now marked as failed in the database without re-attempting to start them
