### ISSUE TITLE
Add filter support for MissionController

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#287]
**Describe the new feature you would like to see**
The Echo API has filter support for their missions endpoint.
This is useful to only get missions from a particular plant or robot, but in order to use it we need to also implement it in our missions controller which calls the echo API.

**Describe the solution you'd like**
See Echo's API [here](https://echohubapi.equinor.com/index.html), the endpoint we are calling is the `robots/robot-plan` endpoint.
We should implement a filtering functionality in our backend to forward this. 
This may be done quick and easy by adding three string parameters with the `[FromQuery]` attribute to our `/missions` endpoint, but ideally we should implement a general filter functionality for our backend, like described by code-maze [here](https://code-maze.com/filtering-aspnet-core-webapi/)

**How will this feature affect the current Threat Model?**

**Comment by aestene** [comment]
Closed after discussion
