### ISSUE TITLE
ScheduledMissions and robots only available after authorizing backend

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#324]
**Describe the bug**
When starting flotilla the scheduled missions did show. However after going to https://localhost:8000/swagger/index.html and clicking authorize there the scheduled missions started and showed.

**To Reproduce**
Start the broker in docker, start the backend outside docker and start the frontend outside docker. Open http://localhost:3001/ and see that the robots and shceduled missions does not show. Open https://localhost:8000/swagger/index.html, click authorize and check http://localhost:3001/ again.

**Expected behavior**
It should not be necessary to authorize the backend in addition to login into Flotilla.

**Screenshots**

**Comment by GodVenn** [comment]
Is there a call to the backend in the frontend console log with a 401 status code returned?

**Comment by GodVenn** [comment]
I did the steps to reproduce and could not reproduce the issue.
@oysand could you verify that this is still an issue?

**Comment by oysand** [comment]
I've had mixed experiences, it seems that sometimes this happens, but not consistently. Usually it happens when it has been some time between starting the application

**Comment by aestene** [comment]
@eivindsjovold will have a look at recreating this bug

**Comment by eivindsjovold** [comment]
Snippet from browser console when this bug occurs: 

![Image](https://user-images.githubusercontent.com/66949993/192986922-40d7f719-14ce-40be-a536-36755e9b6cd5.png)

**Comment by eivindsjovold** [comment]
I agree @GodVenn.
