### ISSUE TITLE
Radix build for flotilla backend is failing

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#338]
Following error:
'Api.Database.Context.FlotillaDbContext'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Pose_Frame'.

**Comment by GodVenn** [comment]
Probably need to migrate the recent database changes to actual SQL database

**Comment by GodVenn** [comment]
Fixed, and we are moving the CI/CD to aurora
