### ISSUE TITLE
Lock frontend control button state to backend mission state

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#386]
**Describe the improvement you would like to see**

As of now, the frontend state for the control buttons is handled in the frontend using enums
``` 
const [status, setStatus] = useState(MissionStatus.Ongoing);
enum ControlButton {Pause, Stop, Play}

const handleClick = (button: ControlButton) => { 
```

This may lead to bugs where frontend control button state and backend mission state do not match.
Fix this by locking frontend button state to backend mission state, and maybe include a loading icon 
while backend is being polled.

**How will this change existing functionality?**
Frontend will accurately portray the backend state

**How will this improvement affect the current Threat Model?**
N/A

**Comment by eivindsjovold** [comment]
Closed by #487
