### ISSUE TITLE
Robot is displayed as `Offline` instead of `Busy`

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#404]
**Describe the bug**
When a mission is scheduled on a robot and it is `Busy` the robot is displayed as `Offline` rather than `Busy`.

**To Reproduce**
Start Flotilla, isar-turtlebot and ISAR and schedule a mission for R2-D2 from the frontend. The robot should show as offline. 

**Expected behavior**
Expect an indication that the robot is busy or in a mission. For example the status `Busy` showing up in a red color. 

**Screenshots**
 In this picture a mission is running on R2-D2 but it is displayed as offline.
![image](https://user-images.githubusercontent.com/14331473/195795704-2351b7ae-3dca-4235-a9e4-f8bfd37f1ff5.png)

**Comment by martinko2369** [comment]
Hi @aestene, i would like to work on this issue.

**Comment by oysand** [comment]
Done
