### ISSUE TITLE
Selecting asset should imply fetching different missions from Echo

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#405]
**Describe the improvement you would like to see**
The selected asset in the dropdown at the top of the page should feed into the request made for missions to Echo. Currently it looks like the default is to always collect the missions for Kårstø.

- Note that no missions should be retrieved if an asset has not been selected
- The user should be informed that there is no selected asset and that one should be selected
- Alternatively the default asset could be set to Kårstø for now and this can be updated later so one is always selected

![image](https://user-images.githubusercontent.com/14331473/195797652-589eb05b-22ab-4d8a-befe-b781dfdcb651.png)

**How will this change existing functionality?**
The asset dropdown will mean something.

**How will this improvement affect the current Threat Model?**
No affect in particular.

**Comment by Eddasol** [comment]
The alternatives when scheduling mission is already filtered but there is no filter for upcoming and ongoing missions
