### ISSUE TITLE
Scheduling multiple missions with remote database means only one mission is executed

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#408]
**Describe the bug**
Scheduling a lot of missions simultaneously using the remote database the robot is not updated to available after a mission has been executed. Thus leaving the rest of the missions as pending. 

**To Reproduce**
1. Start the full deployment stack with the backend in the Staging environment. Bug was seen with isar-turtlebot and has been seen using an actual robot.
2. Schedule multiple missions on the same robot.
3. Wait for the first mission to finish and see the effect.

**Expected behavior**
Once a mission is complete the robot should be set as available and queue the next mission. Eventually all missions should be completed.

**Screenshots**
Log from Flotilla backend showing that the message from ISAR that the mission is complete har been received and that the robot should have been set as available.
![image](https://user-images.githubusercontent.com/14331473/195803170-e00f49a1-7f7e-4690-8f24-0b9f807537ac.png)

Robot `william` is set as "Offline"
![image](https://user-images.githubusercontent.com/14331473/195803391-8dc7c4de-f31c-46fa-b8ee-c58d1ceaed31.png)

Remaining missions on `william` are not started as the robot is marked as busy. 
![image](https://user-images.githubusercontent.com/14331473/195805161-baefb5ac-f21e-45ae-9001-43b5f44a54c3.png)

**Comment by aestene** [comment]
Maybe have a look @oysand?

**Comment by aestene** [comment]
Note that this only occurs using the remote SQL database and not when using the local SQLite database.

**Comment by aestene** [comment]
Note that scheduling a single mission also leaves the robot as busy after the mission has completed so the problem is not dependent on scheduling multiple missions.

**Comment by oysand** [comment]
Works now
