### ISSUE TITLE
Display which robot is assigned to the mission on the front page

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#409]
**Describe the improvement you would like to see**
Would like to see which robot has been assigned to the mission without entering the mission page itself. So if Optimus has a mission it should say Optimus.

In the image we can see two missions scheduled both belonging to Optimus. Debugging requires entering the mission site to see which robot has been assigned the missions.
![image](https://user-images.githubusercontent.com/14331473/195817357-7a9781b5-6790-4033-936d-7b23e6e5f15d.png)

**How will this change existing functionality?**
Improve user friendliness.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by oysand** [comment]
Donw
