### ISSUE TITLE
Display progress in terms of how many steps have been completed

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#410]
**Describe the improvement you would like to see**
Show the progress of the robot mission by displaying how many steps have been completed and how many are left. Currently this is done as a ?/? but actual numbers should be used. 
![image](https://user-images.githubusercontent.com/14331473/195818860-88ea9cad-2777-4e04-9f63-1cf8f5b4033d.png)

**How will this change existing functionality?**
Improved user experience.

**How will this improvement affect the current Threat Model?**
NA

**Comment by oysand** [comment]
Done
