### ISSUE TITLE
Store enum values in database as string instead of int

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#417]
**Describe the improvement you would like to see**
Currently enum values are stored as ints in the database rather than strings. It would be easier to store these as strings automatically which can be performed through value conversions. https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations

Examples of enums this is true for is `RobotModel` and `RobotStatus`.

![image](https://user-images.githubusercontent.com/14331473/196357277-b2b3cd71-d36d-404f-b5e2-d8ac606ed9da.png)

**How will this change existing functionality?**
Easier to interact with the database.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by GodVenn** [comment]
Ints are more scalable for future changes to enums and safer for comparisons - Closing this as discussed in weekly planning.
