### ISSUE TITLE
Present Map in Frontend

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#456]
**Describe the new feature you would like to see**
The map should be presented to the user when entering the robot view page / mission page. The map should show the area the robot is going to perform the mission in and a marker displaying where the robot is.

**Comment by MortFred** [comment]
Arcitecture discussion for this task 06.01.23 led to initial architecture looking like this:


![Image](https://user-images.githubusercontent.com/65544380/211000150-ef28008b-0852-466b-a687-a866e7f624e8.svg)

**Comment by MortFred** [comment]
- [ ] Make Azure blob storage solution with index tags and metadata
- [ ] Implement logic to add a map to new EchoMissions
- [ ] Implement GET RobotMapPosition endpoint
- [ ] Implement GET RobotTagPosition endpoint
