### ISSUE TITLE
Fetch concrete information from backend in the components when needed

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#458]
**Describe the improvement you would like to see**

Let each component ask directly for what they need through an apiCaller and dedicated endpoint, instead of asking for for instance a mission on top level and then pass it down into the components. For example for displaying the robot position in `MapPositionSection.tsx` and also for displaying the task table in `TaskTable.tsx`.
A clear and concise description of the improvement proposal.

**Comment by MortFred** [comment]
Consider this after finishing implementing #456

**Comment by phhuseboe** [comment]
Not blocked anymore @MortFred ?

**Comment by aestene** [comment]
@MortFred

**Comment by anetteu** [comment]
Closing this issue. A new issue should be created if this is a need in the future.
