### ISSUE TITLE
Mission names should be required

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#475]
**Describe the improvement you would like to see**
In the database model the name is not required. This should be made required and necessary migrations for the database performed.

**How will this change existing functionality?**
This will guarantee that the name exists which is our primary identifier of the mission.

**How will this improvement affect the current Threat Model?**
N/A

**Comment by anetteu** [comment]
Duplicate with #419?

**Comment by aestene** [comment]
Agreed, thus closing this one.
