### ISSUE TITLE
Estimated mission duration is wrong

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#484]
**Describe the bug**
The estimated duration of missions is clearly not always correct, as seen from the screenshot. I have not checked whether this is caused by a wrong estimation or invalid start/end times.  

**To Reproduce**
Start flotilla (on commit cd9a9debf7815c1d648ef3f9d12b384530e2be74 when writing this issue), and have a look at the estimated duration of the missions on the front page. 

**Expected behavior**
An reasonable estimated duration of hours. 

**Screenshots**
![Screenshot from 2023-01-04 13-10-36](https://user-images.githubusercontent.com/21355793/210552487-7c54ef76-508a-4466-8e95-351fd02010b2.png)

**Comment by oysand** [comment]
Change estimates from using end time, it should be estimated duration and calculated in the backend

**Comment by GodVenn** [comment]
Should be implemented after #554 .
Then we need no math in the frontend, but rather to use the "Estimated Duration" field from the mission object.

**Comment by Christdej** [comment]
#554 is implemented
