### ISSUE TITLE
Handle refresh tokens for authentication

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#50]
**Describe the bug**
If the user authenticates in the OpenAPI documentation the authentication token will not be automatically refreshed after 1 hours (token timeout). This should be handled. 

**To Reproduce**
- Authenticate in OpenAPI
- Wait 1 hour
- MAke a request

**Expected behavior**
Instead of failing authentication a refresh token is used to authenticate again and from the users POV there is no change.

**Screenshots**
![image](https://user-images.githubusercontent.com/14331473/151368417-d9f0b89c-f4c7-4521-b704-a2e1f080ebd7.png)

**Comment by vetlek** [comment]
Seems like there is no support for refresh tokens in the library that is currently used for authentication.

**Comment by vetlek** [comment]
Is this a real issue though? The API is not supposed to be used from the SwaggerUI except for simple testing in the development, and there is no issues with revoked access tokens when the API is used by clients with secrets. Can't really see the problem with having to authenticate yourself every 60-90 minutes.
