### ISSUE TITLE
Create landing page for non-authorized users

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#505]
**Describe the bug**
Currently, all Equinor employees are authenticated when the log in to frontend. Unauthorized users should be redirected to a landing page where they are asked to apply for access.

**To Reproduce**
Log in to flotilla without being registered as a user in the relevant flotilla Enterprise application(service principal=
**Expected behavior**
Unauthorized users are expected to be redirected to a separate page, and they should not see anything if they naviage to other pages.

**Screenshots**

**Comment by eivindsjovold** [comment]
Related to #504

**Comment by phhuseboe** [comment]
Same as #504
