### ISSUE TITLE
Start-, Stop-, Pause-, and Resume endpoints should be moved to mission controller

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#508]
**Describe the improvement you would like to see**
Right now, the Start-, Stop-, Pause-, and Resume endpoints are under the robotController file.
These are all mission specific operations, and should be moved to missionController file.

**Comment by GodVenn** [comment]
Not sure I agree. Maybe the start mission could be removed as we already have a "schedule mission"

The stop, pause and resume do make sense to keep on the robot because it is also equivalent to "stopping **robot**", "pausing **robot**" and "resuming **robot**"
