### ISSUE TITLE
Logging "info" reporting that backend has succeeded connecting to broker

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#510]
**Describe the improvement you would like to see**
Logging message of type "info" reporting that backend has successfully connected to broker

**How will this change existing functionality?**
Easier to tell when the backend has established connection with broker. See screenshot for possible solution
![image](https://user-images.githubusercontent.com/111290642/213188452-1ab4a895-4630-44f4-9e8d-19380edff4fd.png)

**How will this improvement affect the current Threat Model?**
Will not affect

**Comment by GodVenn** [comment]
This is implemented
