### ISSUE TITLE
Not possible to cancel/pause ongoing mission in flotilla

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#527]
**Describe the bug**
The cancel and pause buttons for ongoing missions in flotilla did not show. For information, the tasks did not update during the missions either, so there was several things that was not working as expected. 

**To Reproduce**
Ran the newest version form main 26.01.2023 locally on the operator laptop with willliam. 

**Expected behavior**
The pause and stop button should be visible and functional both on the ongoing mission card on the front page and at the ongoing mission page. 

**Screenshots**

![26be59f8-eea1-454b-a77f-cf9e38f31e46](https://user-images.githubusercontent.com/21355793/215025469-7d029eb0-3d4d-42da-8ade-1cd9d3471f6c.jpg)

**Comment by oysand** [comment]
I was not able to reproduce this. Tried with the latest version and the version of the 26.01.2023 of flotilla, isar and isar-robot. @phhuseboe @eivindsjovold Do you have any idea what this could be?

**Comment by oysand** [comment]
Worked after pulling the latest version of ISAR
