### ISSUE TITLE
Sort task by planned order

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#532]
**Describe the improvement you would like to see**
Mission tasks in fronend should be sorted by planned order and not as it is now. See screenshot where task 4 is first followed by task 10

**How will this change existing functionality?**
It will look better

**How will this improvement affect the current Threat Model?**
N/A

![image](https://user-images.githubusercontent.com/33518988/215047726-82f8c804-1e47-4036-8f93-3b6b2a7d4966.png)

**Comment by anetteu** [comment]
Duplicate with #530?

**Comment by Eddasol** [comment]
> Duplicate with #530?

Agreed
