### ISSUE TITLE
Send "Initial Pose" to ISAR based on last known position of current deck

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#535]
**Describe the new feature you would like to see**
ISAR should expect to get an initial pose for localization based on the data in Flotilla. 
This will enable operators to "override" the current position of a robot through Flotilla when they move it manually without disturbing ISAR.

Depends on #534 .

**Describe the solution you'd like**
In Isar Service's "Start Mission" function, add the last known pose of the robot's current deck as part of the payload, named "InitialPose" _(of type `IsarPose`)._
ISAR already accepts this as an optional parameter (See screenshot)
![image](https://user-images.githubusercontent.com/57716654/215127570-f2a489fc-24c4-47b1-bb22-931626797890.png)

**How will this feature affect the current Threat Model?**
N/A

**Comment by Eddasol** [comment]
Not needed anymore. Functionality will be covered by #737
