### ISSUE TITLE
Add overpressure status and warning for relevant robots

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#558]
**Describe the new feature you would like to see**
The overpressure status should be visible for the robots were relevant, possibly with an indication of whether the overpressure is reaching a limit (check limits defined for relevant robots). The status should also pherhaps be visible in the relevant mission, and a warning pop up should be considered if a robot is approaching a limit/risk of shut down during a mission. 

**Describe the solution you'd like**

**How will this feature affect the current Threat Model?**
No change.

**Comment by Christdej** [comment]
Preferably a graph (both for battery and pressure).

**Comment by anetteu** [comment]
Close this issue? Should be covered by #673 #674 #675
