### ISSUE TITLE
Add reason text field to mission data structure

### ISSUE THREAD

**Issue by GodVenn** [equinor/flotilla#563]
**Describe the new feature you would like to see**
Add new field `Reason` to missions.
This field can be used to store reasons for warnings or failures for a mission and this information will be useful to store when a mission has such a status.

**Describe the solution you'd like**
A new text field on the mission model. It should **not** be marked with `required`.

**How will this feature affect the current Threat Model?**
It might improve our overview of what errors we are encountering and will hopefully make our solution more robust as a result.

**Comment by Christdej** [comment]
Will call it StatusReason for a clearer understanding of what it does
