### ISSUE TITLE
Control buttons do not appear when mission is started

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#568]
**Describe the bug**
Control buttons do not appear when mission is started. 

**To Reproduce**
Schedule a new mission and have it start.

**Expected behavior**
Control buttons should be present next to the mission title when the mission is ongoing.

**Screenshots**
![image](https://user-images.githubusercontent.com/65544380/218482981-27ef758b-1615-47e6-bcc6-3d840de0a9d5.png)

**Comment by phhuseboe** [comment]
I followed the reproduce step, and the control buttons worked as expected
