### ISSUE TITLE
Send battery- and pressure exceptions from Isar to Flotilla

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#605]
**Describe the new feature you would like to see**
The user should be notified when a mission fails/is paused due to low battery/pressure.
As such, Flotilla backend should have this information when exceptions occur in flotilla

**Describe the solution you'd like**
Make a MQTT topic that published errors to flotilla.

**How will this feature affect the current Threat Model?**
More information will be made available higher up the stack

**Comment by MortFred** [comment]
Question, is sending MQTT-error messages the best way to implement ISAR -> Flotilla communication

**Comment by anetteu** [comment]
See #558

**Comment by GodVenn** [comment]
No longer relevant. This is handled in Flotilla now.
See #722
