### ISSUE TITLE
Can not start mission with isar-robot in Aurora

### ISSUE THREAD

**Issue by tsundvoll** [equinor/flotilla#622]
**Describe the bug**
Mission fails immediately when scheduling to isar-robot

**To Reproduce**
1. In Flotilla, schedule mission on isar-robot in Aurora Dev environment

**Expected behavior**
Mission starting

**Screenshots**
![Screenshot from 2023-02-24 16-18-10](https://user-images.githubusercontent.com/35451859/221216036-262854bd-47f7-4dac-b494-72fa2b3ba06a.png)

**Comment by GodVenn** [comment]
This has been solved
