### ISSUE TITLE
Missions from JS does not schedule

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#627]
**Describe the bug**
Missions from JS does not start

**To Reproduce**
When scheduling echo mission 387 in flotilla, the mission does not start.
This was tested both locally and in the aurora dev environment.

**Expected behavior**
Missions from JS should be able to be scheduled.

**Screenshots**

**Comment by Eddasol** [comment]
It works if changing line 17 in "backend/api/appsettings.json" to: "InstallationCode": "jsv",
