### ISSUE TITLE
Add map for JSP1 weather deck

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#629]
**Describe the improvement you would like to see**
Add map for JSP1 weather deck to visualize robot position and missions at the mentioned deck. 

**How will this change existing functionality?**
No change, just providing new maps. 

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
Fixed by @MortFred
