### ISSUE TITLE
Control buttons inside ongoing mission display 'pause' when it is 'paused', not 'play' as it should

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#636]
**Describe the bug**
Control buttons inside ongoing mission display 'pause' when it is paused, not 'play' as it should.

**To Reproduce**
1. Start a mission
2. Pause mission from the Ongoing Mission front page section
3. Quickly navigate into the ongoing mission card

**Expected behavior**
Control buttons should always render to 'stop'/'play' when 'paused', and 'stop'/'pause' when 'ongoing'

**Screenshots**
![image](https://user-images.githubusercontent.com/111290642/222137173-cd91bcda-bd1c-4016-a22e-738dbdc150d2.png)

**Comment by phhuseboe** [comment]
Note that this is an edge case. Manually refreshing page solves it, but should be automatic

**Comment by phhuseboe** [comment]
Waiting on #505

**Comment by Eddasol** [comment]
Pull #662 solves this issue such that the button get updated, but the buttons are still not disabled as the play/pause-switch is ongoing. This makes it possible to choose pause while there already is an ongoing process to pause, leading to an attempt at pausing while the robot is potentially already paused, causing an 502 error.

Clicking pause within the missioncard followed by going to frontpage and stress testing the pause/play-button will cause error
