### ISSUE TITLE
Order mission queue

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#660]
**Describe the new feature you would like to see**
Currently the missions get picked from the mission queue in a seemingly random order. It would be better if the mission that got added to the queue first get executed first. 

Bonus: Making sure that the order is presented correctly in frontend as well and allowing the user to modify the order of the missions trough drag-and-drop 

**Describe the solution you'd like**

**How will this feature affect the current Threat Model?**

**Comment by aestene** [comment]
Related to #474

**Comment by aestene** [comment]
This is how the order is currently displayed


![Image](https://user-images.githubusercontent.com/14331473/226273675-bbf54e82-c16c-462a-b584-45aff3259b84.png)
