### ISSUE TITLE
Handle 401 errors by redirecting to sign-in-page

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#665]
**Describe the new feature you would like to see**
Error handling of 401 errors by redirecting to sign-in-page.

**Describe the solution you'd like**
401 errors occurs when session token expires, and should trigger error handling redirecting to sign-in-page. 

**How will this feature affect the current Threat Model?**
N/A

**Comment by phhuseboe** [comment]
In the case of session token expiration, refresh tokens should be used

**Comment by Christdej** [comment]
Fixed
