### ISSUE TITLE
Make flotilla listen to pressure updates

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#673]
**Describe the new feature you would like to see**
Some robots require overpressure to be ATEX. The robot package itself is in charge of publishing the current pressure on the topic `isar/{isar_id}/pressure`. Flotilla should listen for MQTT messages on these topics and if one is received it should update the pressure value for that robot in the database. It should also know for that robot which pressure limits are relevant such that the frontend may use that to display warnings etc.

- Add pressure as an optional field for the robot model
- Add an event handler for the pressure message which updates the field in the robot model
- Add two optional fields for the robot which is warning limit for pressure and lower limit for pressure

**Describe the solution you'd like**

**How will this feature affect the current Threat Model?**
N/A

**Comment by Eddasol** [comment]
- [ ] Add pressure level #689 
- [ ] Add pressure limits
