### ISSUE TITLE
Display pressure status inside mission in frontend

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#674]
**Describe the new feature you would like to see**
The pressure status should be displayed on the mission page for that robot.

- If there is no pressure associated with the robot nothing should be displayed
- A suggestion is to place the pressure beside the battery status as it is now
- If the mission has finished there is no reason to display the pressure and it should be hidden
- The display should change color depending on the limits for pressure for that robot (see #673)

The design should be verified with @mariannewiggen 

**Describe the solution you'd like**

**How will this feature affect the current Threat Model?**
N/A

![image](https://user-images.githubusercontent.com/14331473/226166584-15fdfb05-33b0-40a3-b864-bbd5686e8320.png)

**Comment by aestene** [comment]
This relies on pressure information made available through the backend by #673

**Comment by Eddasol** [comment]
#690  displays the pressure in the mission page but without considering the warning limit
