### ISSUE TITLE
Display pressure in RobotCards in frontend

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#675]
**Describe the improvement you would like to see**
If a robot has pressure information (the robot needs to be pressurized and is publishing the pressure through MQTT) the current pressure should be displayed in the `RobotCard` component. A suggestion is to display it with a suitable symbol above or beside the battery status as it is displayed now. If there is no pressure nothing should be displayed. 

Based on the limits for pressure defined for that robot the symbol should change color. Ultimately, there should be a warning if the robot is reaching these limits but that does not have to be part of the initial implementation. See #673 for suggestions on adding pressure limits. 

The design should also be verified with @mariannewiggen 

**How will this change existing functionality?**
Pressure is displayed beside or above battery status

**How will this improvement affect the current Threat Model?**
N/A

![image](https://user-images.githubusercontent.com/14331473/226166283-4a90b73c-da99-40b9-b9ec-b86eefbd3f11.png)

**Comment by aestene** [comment]
This issue depends on #673 to make available the pressure updates through the backend.

**Comment by anetteu** [comment]
to #558

**Comment by aestene** [comment]
Correct, I will close #558.

**Comment by aestene** [comment]
Note comment by @Christdej on #558 where there was a suggestion to include a graph. My proposal is to wait with that and we can generate the graph from the timeseries database once that is in place.
