### ISSUE TITLE
Status message should let us know when battery threshold has been activated

### ISSUE THREAD

**Issue by MortFred** [equinor/flotilla#700]
**Describe the improvement you would like to see**
When the battery runs below threshold in the isar-robot package, a failed mission error is displayed.
This should instead say "Battery too low to continue" or something along those lines.

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/65544380/226953333-c4d617b3-c79d-459e-b916-386bb5b25b73.png)

**Comment by GodVenn** [comment]
Related to https://github.com/equinor/flotilla/pull/695

**Comment by aestene** [comment]
battery threshold has been removed for now.
