### ISSUE TITLE
Robots show as available, when unavailable

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#701]
**Describe the bug**
Robot show as available, when it is in fact unavailable

**To Reproduce**
Disconnect robot in staging environment, and see that the robot-card still shows that the robot is available

**Expected behavior**
Robot should show as offline when the robot is turned off

**Screenshots**
![image](https://user-images.githubusercontent.com/48381132/226983384-345a67a0-0d43-4df2-a8c8-0a0944fb7ec3.png)

**Comment by GodVenn** [comment]
This is covered by https://github.com/equinor/isar-taurob/issues/163

**Comment by GodVenn** [comment]
Closed by https://github.com/equinor/isar-taurob/issues/163
