### ISSUE TITLE
Improve Historic Missions list

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#711]
**Describe the improvement you would like to see**
Would be nice if the Historic Missions list was longer (see screen shot where only you can see 4 missions) and wider.
Also maybe show for instance 20 missions, then add paging so show the next 20. Like pagination normally works.
Also in the future add the option to filter based on the different columns.

**How will this change existing functionality?**
Will make it much easier to look at historic missions and get an overview.

![image](https://user-images.githubusercontent.com/48381132/227730586-da9c88e1-2ff4-4ded-b573-4eae8dcbfe37.png)

**Comment by GodVenn** [comment]
This was solved in #714
