### ISSUE TITLE
Add robot model class to database

### ISSUE THREAD

**Issue by UsamaEquinorAFK** [equinor/flotilla#721]
**Describe the new feature you would like to see**

Include a robot model class in database (instead of an enum). Robot model class defines robot model specific characteristics, add pressure limit and battery limit  as new characteristics.  

**Describe the solution you'd like**
NA

**How will this feature affect the current Threat Model?**
NA

**Comment by UsamaEquinorAFK** [comment]
#727 Added the variables to the Robot class instead of robot model as that is an enum and cant be initialized as a static class.

**Comment by GodVenn** [comment]
After discussion the class will still be added and enum included in class
