### ISSUE TITLE
Mission tasks random order

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/flotilla#726]
**Describe the bug**
All tasks in mission in echo is shown as task #1. They seem to be randomly ordered(running the same mission twice yields different order)

**To Reproduce**
Run mission in flotilla, obsere that all tasks are labelled as number one.  Run twice and observe ordering has changed.

**Expected behavior**
Mission identical each time

**Screenshots**
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/66949993/229365342-935510e4-4edc-4789-a358-46228fd1f35b.png)

**Comment by GodVenn** [comment]
This is a bug in Echo, they said they had fixed it, but I will contact them again @eivindsjovold

**Comment by GodVenn** [comment]
Awaiting fix from echo

**Comment by aestene** [comment]
@Eddasol will test if this has been fixed with new missions

**Comment by Eddasol** [comment]
This there

**Comment by Eddasol** [comment]
Changing the order of some of the tags when creating the mission in echo will prevent this issue

**Comment by andchiind** [comment]
This is partly solved in this PR https://github.com/equinor/flotilla/pull/817

**Comment by oysand** [comment]
Not experienced in a while, will close the issue and open a new one if needed
