### ISSUE TITLE
Quaternions in flotilla backend should be calculated with clockwise rotation, not counterclockwise

### ISSUE THREAD

**Issue by phhuseboe** [equinor/flotilla#730]
**Describe the bug**
The convertion from Echo's Axis-angle representation to quaternion makes the calculated pose rotate counterclockwise instead of clockwise, making the robot move to wrong pose

**To Reproduce**
1. Run mission with taurob or turtlebot
2. Observe that it rotates to wrong pose by doing counterclockwise rotation, not clockwise

**Expected behavior**
The resulting pose should be set following clockwise rotation

**Proposed solution**
Negate the angle used in convertion from Axis-Angle to quaternions

**Screenshots**
N/A

**Comment by aestene** [comment]
Uncertain if this issue is related to quaternions and their rotations. Would like a discussion @phhuseboe.

Until then the issue will be kept in TODO.

**Comment by aestene** [comment]
Blindzone?

**Comment by phhuseboe** [comment]
@aestene It was observed that the base oriented itself north when we told it to orient itself south. We have converted the axis-angle representation of orientation to quaternions, following the right hand rule. Echo's coordinate frame follows the left-hand rule, and I believe that this makes it turn the opposite direction

**Comment by aestene** [comment]
We will test this with the robot today.
