### ISSUE TITLE
Backend crashing if robot pod is failing to start

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#732]
**Describe the bug**
The backend hosted service which is in charge of scheduling the missions that are queued from the frontend will crash if the robot is not actively running (pod not starting). This in turn causes the entire backend to crash without recovery.

**To Reproduce**
1. Run the system in Aurora with the robot pod failing (for example delete a secret in the keyvault so it is unable to find the secret when starting the pod)
2. Schedule a mission from the frontend to that robot
3. The mission will be in the list but not started
4. The backend log will give what is displayed in the picture below

**Expected behavior**
There should be a timeout when attempting to schedule the mission which if hit should trigger some error revocery.
- It may attempt to reschedule the mission x times
- It may then decide it was unable to schedule the mission and mark it as failed
- Some user feedback should be provided in this case

**Screenshots**
![Screenshot from 2023-04-11 10-29-57](https://user-images.githubusercontent.com/14331473/231102596-14e85b60-12ef-49c9-b7af-58e409d56aac.png)

**Comment by GodVenn** [comment]
Cannot recreate, flotilla backend should have error handling for this in place, closing issue after confirming with issue author @aestene
