### ISSUE TITLE
Remove robot id from schedule mission dialog

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#756]
**Describe the improvement you would like to see**
When scheduling missions the robot id is presented under select robot. This should be modified to something like  "robotname (model)" e.g. "William (Taurob inspector)"
![image](https://user-images.githubusercontent.com/33518988/233139576-53f09060-07ec-4294-bca8-ad36784c99ba.png)

**How will this change existing functionality?**
This would be more informative for the user

**How will this improvement affect the current Threat Model?**

**Comment by GodVenn** [comment]
What if there are several robots of the same type? Since ID is the only real identificator we have, I think it should be part of the list, although maybe we can reduce it to the first 5 symbols and put it in parantheses or something?
