### ISSUE TITLE
Add return to home / safe zone functionality

### ISSUE THREAD

**Issue by aestene** [equinor/flotilla#769]
**Describe the new feature you would like to see**
It should be possible to command the robot to return to a safe zone through Flotilla in cases where the mission should be aborted and the robot should move to a location which is considered secure. A specific example is in case of an alarm where the robot should move out of emergency escape routes it may be blocking. 

**Describe the solution you'd like**
An asset deck should have defined locations which are safe zones that the robot may be commanded to return to. An example of a safe zone could be the docking station where the robot usually lives. 

The frontend should then have a button for the robot which is active when relevant. This button will cancel the currently executing mission and schedule a mission for the robot to return to a defined safe zone. 

- [ ] #1046 

**How will this feature affect the current Threat Model?**
NA

**Comment by Christdej** [comment]
Needs more work

**Comment by mariannewiggen** [comment]
Suggest adding:
- A “Send robot to safe zone” button
- Pop-up for make sure to send robot to safe zone  
- Orange banner for when the robot is on its way to the safe zone
- Green banner for when robot is in safe zone
- Change “Send to safe zone” buttton to “ Safe to continue missions” when robot is on the way to safe sone or in safe zone
- Banner to confirm that the robot has continued with its missions

Link to figma: https://www.figma.com/file/q6vsNRogzV6r9vTCCDsocd/Robot-Missions?type=design&node-id=5318%3A164685&mode=dev

![Image](https://github.com/equinor/flotilla/assets/112481380/9a53803d-e63c-4d40-b04a-e61f2851835a)
![Image](https://github.com/equinor/flotilla/assets/112481380/e4682fa4-a936-4657-9f98-529e3cbc4aa8)
![Image](https://github.com/equinor/flotilla/assets/112481380/a86890d8-8607-4c32-b91c-495b9c95e37d)
![Image](https://github.com/equinor/flotilla/assets/112481380/6ea76dfd-eff7-41f5-9069-44c41ae5bba6)
![Image](https://github.com/equinor/flotilla/assets/112481380/8de79274-45a8-4855-b9a6-deca0c4434dd)
![Image](https://github.com/equinor/flotilla/assets/112481380/beb5edee-b882-4dc0-a1ec-952dd44e615d)

**Comment by aestene** [comment]
The final part of this will be handled by #950 so we close this one.
