### ISSUE TITLE
Use of capital letter of function names is not consistent in frontend

### ISSUE THREAD

**Issue by Eddasol** [equinor/flotilla#796]
**Describe the improvement you would like to see**
Change function names to correspond to best practice
![bestpractice](https://github.com/equinor/flotilla/assets/33518988/50c987d3-1948-451e-972c-e58cd5d01a67)

**How will this change existing functionality?**
A clear and concise description on how this will affect current functionality.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
Closing as we are using a different convention to AWS
