### ISSUE TITLE
Missions are not always FIFO in missions queue

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#807]
**Describe the bug**
When scheduling missions through the `/missions/costum` endpoint in the API, the missions are added and executed in an alphabetical order. When missions are rescheduled from the flotilla gui, they are scheduled at the end of the queue.

**To Reproduce**
Schedule missions with the `/missions/custom` endpoint. The missions will be added to the mission queue and executed in alphabetical order.

**Expected behavior**
Mission queue should be FIFO. When missions are rescheduled from the flotilla gui, they are correctly scheduled at the end of the queue. Scheduling mission with the `/mission/costum` endpoint should result in the same behaviour.

**Screenshots**
Screenshots: Mission 8 and 9 is scheduled. Then, mission 1 is added with the `/missions/custom` endpoint, and then mission 2. These missions are added to the queue in alphabetical order, resulting in the following queue: 1-2-8-9. It should have been FIFO, 8-9-1-2. In the last screenshot, mission 4 is added using the reschedule function in flotilla frontend. The mission is added to the end of the queue, giving the FIFO queue 8-9-4.
![IMG_0229](https://github.com/equinor/flotilla/assets/21355793/635d6ad1-4049-4be7-b93b-5619072994dc)
![IMG_0231](https://github.com/equinor/flotilla/assets/21355793/83efc851-8c20-498f-b5e9-151681035acb)
![IMG_0234](https://github.com/equinor/flotilla/assets/21355793/f3ae0f5b-96f6-4af5-8d34-4235daf397b9)
![IMG_0238](https://github.com/equinor/flotilla/assets/21355793/9c666b7d-4155-4d7b-b7f9-f7f1344dc55f)

**Comment by Eddasol** [comment]
Making desired start time as optional for custom missions and setting it to now as it is scheduled will solve this issue
