### ISSUE TITLE
Create a new page view for assets

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#835]
**Describe the new feature you would like to see**
There should be a page per asset (eg. JSV) that displays information on what decks are asssociated with it.

**Describe the solution you'd like**
Once an asset has been selected, there should be a button which leads to the new page. For now the decks can be displayed as a list of buttons. In the future when a user clicks on a deck information regarding when the last mission was run and when the next scheduled mission should run, should be shown.

**How will this feature affect the current Threat Model?**

**Comment by Eddasol** [comment]
Covered by #839
