### ISSUE TITLE
Localization map needs a heading

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#850]
When localizing the robot, there is no indication which way the robot should be facing. We should change the dot in the figure from a circle with the number 1 in it, to the same we use for the robot in the normal map, but with the heading the localization is expecting.

![image](https://github.com/equinor/flotilla/assets/48381132/1edaeb93-1e14-47b7-9bbd-a8975289726c)
![image](https://github.com/equinor/flotilla/assets/48381132/bec508ff-363f-4884-8db4-92e971e118aa)

**Comment by Aswin-Inigo** [comment]
asdf

**Comment by Eddasol** [comment]
![Image](https://github.com/equinor/flotilla/assets/33518988/c028dc64-33f2-47c6-ae32-bd4af590932b)

Would this be preferred? @Christdej

**Comment by Christdej** [comment]
That would be perfect yes! @Eddasol
