### ISSUE TITLE
Localize as part of mission

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#851]
We starting a echo-mission it would be beneficial to add a localization step at the start of the mission, and also add the localization position as the last step of the mission. This was the operators only have to put the robot in the correct position, run the mission, come back in a few hours and the robot will be at the position it was left unless it got stuck somewhere in the mission.

Also need this functionality for custom-missions.
This functionality needs to be optional or configurable as not all robots need to localize and has a docking station.

Would ideally happen behind the scenes. Might require changes to isar and robot repos.

This issue might compliment or conflict with #852

**Comment by Eddasol** [comment]
Not sure if this is desired functionality. Should be discussed before implementing

**Comment by oysand** [comment]
To be handled in #950
