### ISSUE TITLE
Live update on Telementry data

### ISSUE THREAD

**Issue by OleDrange** [equinor/flotilla#860]
**Describe the improvement you would like to see**
To see the updated pressure and battery of the robot, we have to refresh the page. Should be live data changing without the need to refresh the page.
**How will this change existing functionality?**
Easy to see live pressure and battery.

**How will this improvement affect the current Threat Model?**

**Comment by aestene** [comment]
D you mean on the mission page or on the robot card? @OleDrange

**Comment by OleDrange** [comment]
The problem was in the RobotPage, but I fixed it in commit d9d573e. So I close this card.
