### ISSUE TITLE
In aurora, robotpage and mission page get blank when refreshing

### ISSUE THREAD

**Issue by OleDrange** [equinor/flotilla#861]
**Describe the bug**
In Aurora, robotpage and mission page get blank when refreshing. 

**To Reproduce**
In aurora https://shared.aurora.equinor.com/robotics-staging-frontend/ go to robotpage/ missionpage and press F5 or refresh. This gives a blank page.

**Expected behavior**
Refreshing should not give a blank page

**Comment by aestene** [comment]
Duplicate #414
