### ISSUE TITLE
Store "analysis_types" when storing inspections

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#868]
**Describe the new feature you would like to see**
When we schedule a mission from Flotilla the `Inspection` objects within the mission contains a field called `AnalysisTypes`. This field is intended to contain a string which implies what type of analysis should be executed on the file produced by the inspection.
- The field `AnalysisTypes` should be propagated through the system such that it is stored with the final file in the JSON metadata file https://github.com/equinor/flotilla/blob/main/backend/api/Database/Models/Inspection.cs#L48-L51
- This implies that the `AnalysisTypes` needs to be propagated down to ISAR and from ISAR into the metadata file which is associated with the inspection. See https://github.com/equinor/isar/blob/main/src/isar/storage/utilities.py#L26-L64

**Describe the solution you'd like**
- The end result should be that we have the information needed in the metadata file to decide which analysis method should be executed for the given file, or that no analysis should be performed.

**How will this feature affect the current Threat Model?**
- Nothing in particular to mention here

**Comment by aestene** [comment]
Added thorough description.

**Comment by UsamaEquinorAFK** [comment]
How will we test this functionality ? @Christdej  @aestene

**Comment by Christdej** [comment]
You create a MockMission with the analysis field populated, and see that it is sent to ISAR correctly =)

**Comment by UsamaEquinorAFK** [comment]
https://github.com/equinor/isar/pull/484 - ISAR implementation
https://github.com/equinor/flotilla/pull/946 - Flotilla implementation

**Comment by UsamaEquinorAFK** [comment]
New flotilla implementation: https://github.com/equinor/flotilla/pull/979

**Comment by anetteu** [comment]
This issue is moved to Done in the board, but not closed. Can it be closed? Moving it to the new column on board to force an evaluation during planning.

**Comment by oysand** [comment]
Should have been closed
