### ISSUE TITLE
Flotilla task status is not updated to started

### ISSUE THREAD

**Issue by mrica-equinor** [equinor/flotilla#887]
**Describe the bug**
On staging, flotilla first task status is not updated to started and goes immediately to successful

**To Reproduce**
Send custom mission to staging 

**Expected behavior**

**Screenshots**

**Comment by anetteu** [comment]
I have observed that this does not always happen if the 'TaskOrder' of the first inspection is not '0'. Will continue to observe if this always happens when 'TaskOrder = 0' for the first task, and only then.

**Comment by anetteu** [comment]
Covered by #931
