### ISSUE TITLE
Improve the appearance on small touch screen/iPhone

### ISSUE THREAD

**Issue by anetteu** [equinor/flotilla#908]
**Describe the improvement you would like to see**
The frontend design and components are not all optimized for small touch screens/iPhones. Not all components are easy to adjust with the current design as they have a lot of content. It should, however, be considered to make the needed changes in design and implementation to improve the user experience on small touch screens/iPhones. An example is adjustment of the header menu. This new issue is created to represent the need of a good user experience on iPhones. Some related issues are:

- [x] #808 
- [x] #906 
- [x] #900 
- [x] #901 
- [x] #1009 
- [x] #898 

**How will this change existing functionality?**
A clear and concise description on how this will affect current functionality.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by andchiind** [comment]
Here we need to involve UX design

**Comment by anetteu** [comment]
#1009
