### ISSUE TITLE
The localisation options should only list areas which have available maps and boundaries

### ISSUE THREAD

**Issue by andchiind** [equinor/flotilla#938]
**Describe the bug**
We currently get a 404 and no user feedback when selecting an area that lacks a map

**To Reproduce**
Select AC310

**Expected behavior**
AC310 and the other areas with missing maps should not be listed

**Screenshots**
![image](https://github.com/equinor/flotilla/assets/20266900/ca4b0758-3d86-41a6-8c5c-75f40e3933cd)

**Comment by oysand** [comment]
Might not be relevant after #950
