### ISSUE TITLE
Make areaName optional for mission scheduling

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#939]
**Describe the improvement you would like to see**
Scheduling a mission should not require the areaName.

**How will this change existing functionality?**
Currently the areaName is required and will fail the mission scheduling. The area should be determined based on the TAG's in the mission.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by oysand** [comment]
![image](https://github.com/equinor/flotilla/assets/32652118/82569986-b82b-429c-8cea-5e4376e15752)

**Comment by andchiind** [comment]
I think this can be closed, right?

**Comment by anetteu** [comment]
@oysand closing issue due to lack of detailed description
