### ISSUE TITLE
Cancel mission and return home on low battery

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#951]
**Describe the new feature you would like to see**
When running low on battery the robot should abort any ongoing mission and return to the home position/localization spot for the specific deck. When this happens the mission queue should be cleared as needed from the localization feature #950 

**Describe the solution you'd like**
If you have an idea of how to implement the feature please describe it here.

**How will this feature affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
@oysand This will be closed as it requires further details to be ready for implementation
