### ISSUE TITLE
Only schedule mission on the same deck at once

### ISSUE THREAD

**Issue by oysand** [equinor/flotilla#998]
The robot currently need to operate only at one deck at the time. In order to ensure this the mission in the mission queue for the robot need to only be on the same deck. If there are existing missions in the queue from a different deck, these need to be cleared from the queue and the robot placement needs to be confirmed for this new deck.

**Comment by andchiind** [comment]
I'm confused. Are you saying we should both clear missions on other deck but also confirm the robot on this new deck? Or is this issue that the user should be notified if they attempt to queue missions for a deck the robot is not currently localised on and that these missions should not be put on the queue? And you then want to clear the queue if the robot is localised again on a different deck?

**Comment by oysand** [comment]
This is meant make sure that when we ask the user to confirm that the robot is placed at the correct deck, it is only meaning one deck. This issue is two intertwined with the other issues to split up. Will therefore close it and try to write some new ones
